/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAuthRouteImport } from './routes/admin-auth'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoacoesRouteImport } from './routes/doacoes'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as HistoriaRouteImport } from './routes/historia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin-auth',
  path: '/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacoesRoute = DoacoesRouteImport.update({
  id: '/doacoes',
  path: '/doacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-auth': typeof AdminAuthRoute
  '/agendamento': typeof AgendamentoRoute
  '/ao-vivo': typeof AoVivoRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/doacoes': typeof DoacoesRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-auth': typeof AdminAuthRoute
  '/agendamento': typeof AgendamentoRoute
  '/ao-vivo': typeof AoVivoRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/doacoes': typeof DoacoesRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-auth': typeof AdminAuthRoute
  '/agendamento': typeof AgendamentoRoute
  '/ao-vivo': typeof AoVivoRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/doacoes': typeof DoacoesRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-auth'
    | '/agendamento'
    | '/ao-vivo'
    | '/contato'
    | '/dashboard'
    | '/doacoes'
    | '/galeria'
    | '/historia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-auth'
    | '/agendamento'
    | '/ao-vivo'
    | '/contato'
    | '/dashboard'
    | '/doacoes'
    | '/galeria'
    | '/historia'
  id:
    | '__root__'
    | '/'
    | '/admin-auth'
    | '/agendamento'
    | '/ao-vivo'
    | '/contato'
    | '/dashboard'
    | '/doacoes'
    | '/galeria'
    | '/historia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AoVivoRoute: typeof AoVivoRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  DoacoesRoute: typeof DoacoesRoute
  GaleriaRoute: typeof GaleriaRoute
  HistoriaRoute: typeof HistoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-auth': {
      id: '/admin-auth'
      path: '/admin-auth'
      fullPath: '/admin-auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacoes': {
      id: '/doacoes'
      path: '/doacoes'
      fullPath: '/doacoes'
      preLoaderRoute: typeof DoacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRoute,
  AgendamentoRoute: AgendamentoRoute,
  AoVivoRoute: AoVivoRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  DoacoesRoute: DoacoesRoute,
  GaleriaRoute: GaleriaRoute,
  HistoriaRoute: HistoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
